version: "3.8"
services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - postgis

volumes:
  postgis-data:
    driver: local
